### ISSUE TITLE
Proxmox tags as label

### ISSUE THREAD

**Issue by peschmae** [thegeeklab/prometheus-pve-sd#167]
With the introduction of tags in Proxmox, I'm currently playing around a bit with ways to make use of them in my toolchain.

The `exclude_tags` option is already really nice, but I would also like to be able to make more use of them.
Exposing the tags from proxmox as `__meta_pve_tags` (probably as a comma separated list), would enable to filter on tags in prometheus, and also define alert routing dependent on the tags from proxmox (or silence a host all together, while still enabling it for monitoring, eg. during the inital setup)

I'm currently playing around a bit locally, and will create a pull request when I think the implemtation is ready.
If you have any input how you would like to have such a feature implementd, just leave me a comment @xoxys

**Comment by xoxys** [comment]
I think a comma or space separated list should work, no strong opinion yet :) Would like to see some usage examples/prometheus config snippets on how to use it in the docs if you have time for it. 

What I could think of using it would be something like `__meta_pve_tags=alert:team-1 group:cluster-1` and a prometheus config like this:

```
  relabel_configs:
      - source_labels:
          - __meta_pve_tags
        regex: ".*group:(\S*)"
        target_label: "group"
        replacement: "${1}"
```

But you might have other ideas in mind how to use it and I guess that might be helpful for others as well.
